#!/bin/bash

set -x

dir=$(cd `dirname $0` && pwd)

# symlink rbenv default gems file
mkdir -p ~/.rbenv
ln -s $dir/default-gems ~/.rbenv/default-gems

# symlink bundler config file
mkdir -p ~/.bundle
ln -s $dir/bundler ~/.bundle/config

# symlink rspec config file
ln -s $dir/rspec ~/.rspec

# symlink spring config file
ln -s $dir/spring.rb ~/.spring.rb

# symlink rc files
ls $dir/*rc | while read path; do ln -s $path ~/.$(basename $path); done
