#!/bin/bash

dir=$(cd `dirname $0` && pwd)

# Symlink rc files
ls $dir/*rc | while read path; do ln -s $path ~/.$(basename $path); done

# Run install scripts in sub-directories
ls $dir/**/install | while read file ; do $file ; done
