#!/bin/bash

set -x

dir=$(cd `dirname $0` && pwd)

# symlink ctags config directory
if ! test -d ~/.ctags.d; then
  ln -s $dir/ctags ~/.ctags.d
fi

# symlink editorconfig file
ln -s $dir/editorconfig ~/.editorconfig

# symlink agignore file
ln -s $dir/agignore ~/.agignore

# Symlink rc files
ls $dir/*rc | while read path; do ln -s $path ~/.$(basename $path); done

# Run install scripts in sub-directories
ls $dir/**/install | while read file ; do $file ; done
