#!/bin/bash

set -x

if test "$(uname)" != "Darwin" ; then
  exit
fi

# Copy custom key bindings and keyboard layout to library
# Most significantly, this remaps section sign § to hash #
# Keyboard layout must go to shared library to work with all apps
cp -R ~/dotfiles/mac/Library/KeyBindings ~/Library/
sudo cp ~/dotfiles/mac/Library/Keyboard\ Layouts/* /Library/Keyboard\ Layouts/

# Install and enable login and logout hooks to mute sound on startup
sudo cp ~/dotfiles/mac/loginhook /usr/local/bin/
sudo cp ~/dotfiles/mac/logouthook /usr/local/bin/

sudo defaults write com.apple.loginwindow LoginHook /usr/local/bin/loginhook
sudo defaults write com.apple.loginwindow LogoutHook /usr/local/bin/logouthook

source set_defaults
