#!/bin/bash

set -x

if test "$(uname)" != "Darwin" ; then
  exit
fi

# Copy library files (key bindings and keyboard layout)
cd ~/dotfiles/mac && cp -R Library ~/

# Install and enable login and logout hooks to mute sound on startup
sudo cp ~/dotfiles/mac/loginhook /usr/local/bin/
sudo cp ~/dotfiles/mac/logouthook /usr/local/bin/

sudo defaults write com.apple.loginwindow LoginHook /usr/local/bin/loginhook
sudo defaults write com.apple.loginwindow LogoutHook /usr/local/bin/logouthook

source set_defaults
