set nocompatible                  " Must come first because it changes other options.

set encoding=utf-8                " Force utf8
set nobomb                        " but don't bother with a BOM

set nomodeline

set cursorline                    " Highlight the cursor line

set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set wildignore=*~,*.o,*.log,*.aux,*.dvi,*.pdf

" default to two spaces rather than tabs
set tabstop=2 softtabstop=2 shiftwidth=2 expandtab

set ttyfast                       " Assume a fast terminal connection

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

runtime macros/matchit.vim        " Load the matchit plugin.

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
"set hlsearch                      " Highlight matches.

set nowrap                        " Turn off line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location

set laststatus=2                  " Show the status line all the time
" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-40(\ \ char:\ %03.3b\/%02.2B\ \ col:\ %c-%v\ \ line:\ %l-%L\ %)\ %P

set t_Co=256
colorscheme wombat256mod

"let TList_Auto_Open = 1
let Tlist_Exit_OnlyWindow = 1
let Tlist_Show_One_File = 1
"let tlist_spec_settings = 'Rspec;c:describe;d:context;f:it'

" Tab mappings.
map <leader>tt :tabnew<cr>
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>to :tabonly<cr>
map <leader>tn :tabnext<cr>
map <leader>tp :tabprevious<cr>
map <leader>tf :tabfirst<cr>
map <leader>tl :tablast<cr>
map <leader>tm :tabmove

" Buffer mappings.
map <C-right> <ESC>:bn<CR>
map <C-left> <ESC>:bp<CR>

" Go to File (command-t plugin)
map <Leader>f :CommandT<Enter>

" Toggle taglist with <leader>t
map <leader>t :TlistToggle<Enter>

" Toggle NERDTree with <leader>n
map <leader>n :NERDTreeToggle<Enter>

" Toggle ZoomWin with <leader>z
map <leader>z :ZoomWin<Enter>

"if has("autocmd")
"  :autocmd BufWritePre *.rb,*.erb,*.rhtml,*.html :let save_cursor = getpos(".") | %s/\s\+$//e |  call setpos('.', save_cursor)
"endif

" Controversial...swap colon and semicolon for easier commands
"nnoremap ; :
"nnoremap : ;

"vnoremap ; :
"vnoremap : ;

" Automatic fold settings for specific files. Uncomment to use.
" autocmd FileType ruby setlocal foldmethod=syntax
" autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2

