packadd friendly                  " load friendly defaults (must come first)

set nomodeline                    " No modelines (potential for security issues)

set textwidth=80                  " Default textwidth, override using .editorconfig

set writebackup                   " Create backups before overwriting files
set nobackup                      " But don't retain backups after writing
set directory=$HOME/.vim/tmp//    " Keep swap files in one location
set backupdir=$HOME/.vim/tmp//    " And backups in the same place

if has('gui_running')
  colorscheme PaperColor          " High contrast light bg colors for gui
elseif $TERM_PROGRAM =~# 'iTerm'
  colorscheme solarized           " Match dark iTerm color scheme locally
elseif $SSH_CLIENT != ''
  colorscheme jellybeans          " Distinct color scheme for ssh sessions
endif

set nofoldenable                  " Open all folds by default
set foldlevel=99                  " Don't open/close all folds at same indent
set foldlevelstart=99             " Reset fold level when opening new files
set foldmethod=indent             " Keep it simple stupid, just fold on indent
set foldignore=''                 " Don't ignore # when folding on indent

set updatetime=1000               " Default updatetime for gitgutter and friends

" Sign column configuration - condition copied from coc.nvim readme
if has("nvim-0.5.0") || has("patch-8.1.1564")
  " Merge sign column and number column if supported
  set signcolumn=number
else
  " Otherwise at least use same colours as number column
  hi! link SignColumn LineNr
endif

" Custom status line, show relative file path and file type
set statusline=%<%.99{expand('%:~:.')}\ \%h%w%m%r%{get(g:,'ZoomWin_statusline','')}\ %=\ %{&ft}\ %l\:\%-c\ %P

" Keep timeoutlen short enough to make WhichKey menu appear promptly, but not
" so short that it makes it almost impossible to complete multi-key mappings
set timeoutlen=1000

" Set ttimeoutlen, primarily to make it faster to exit popup windows
set ttimeoutlen=100

" map leader to comma so it's in the same position on all keyboards
let mapleader = ","

" use normal rather than hanging indent for multiline ruby assignment, i.e.
" let x = if foo    --NOT--    let x = if foo
"   bar                                  bar
" end                                  end
let g:ruby_indent_assignment_style = 'variable'

" Disable vim-visual-multi mappings, except CTRL-n (see :h vm-find-word)
let g:VM_default_mappings = 0

" Disable indentLine plugin by default, toggle with <leader>ti
let g:indentLine_enabled = 0

" Use same highlighting for indent lines as used for whitespace listchars
let g:indentLine_defaultGroup = 'SpecialKey'

" Disable conceal for json and markdown, indentLine sets conceallevel to 2, so
" enabling it will conceal some characters in filetypes with built in support
" (I find this acceptable, I don't use conceal, I prefer some kind of preview)
let g:vim_json_conceal=0
let g:markdown_syntax_conceal=0

" Tell vim-qf to enable ack.vim style mappings in quickfix window
let g:qf_mapping_ack_style = 1

" Tell vim-qf to use a fixed window size (default 10)
let g:qf_auto_resize = 0

" Tell vim-qf not to mess with loclist positioning (1 qflist, many loclists)
let g:qf_loclist_window_bottom = 0

" Tell QFEnter to skip some filetypes when choosing window to open
" Note: plugin required because vim only reuses normal buffers when opening
" files from quickfix windows, which does not work well with bufexplorer etc.
let g:qfenter_exclude_filetypes = ['nerdtree', 'tagbar', 'scratch']

" Tell QFEnter to move to next usable window rather than simply echo an error
" when attempting to open a file in a window matching an excluded filetype
let g:qfenter_excluded_action = 'next'

" Open WhichKey menu for leader mappings after timeoutlen (500ms)
nnoremap <silent> , :WhichKey ','<CR>

" Define dictionary with prefix names for leader mappings
call which_key#register(',', "g:which_key_map")
let g:which_key_map =  {}
let g:which_key_map.f = { 'name' : '+fzfind' }
let g:which_key_map.t = { 'name' : '+toggle' }
let g:which_key_map.w = { 'name' : '+window' }

" Disable caching of WhichKey menus - allow for buffer local mappings
let g:which_key_run_map_on_popup = 1

" Run native command when mapping not defined (required for WhichKey 'g')
let g:which_key_fallback_to_native_key = 1

" Disable default bullets.vim mappings, clashes with other mappings
let g:bullets_set_mappings = 0

" Add custom bullets mappings that don't clash with other mappings
function! InsertNewBullet()
  InsertNewBullet
  return ''
endfunction
autocmd FileType markdown,text,gitcommit
  \ inoremap <buffer><expr> <cr> (pumvisible() ? '<C-y>' : '<C-]><C-R>=InsertNewBullet()<cr>')|
  \ nnoremap <buffer> o :InsertNewBullet<cr>|
  \ nnoremap cx :ToggleCheckbox<cr>

" don't automatically save session on exit in non-gui vim
let sessionman_save_on_exit=0

" minimalist sessions list, hide mappings help
let sessionman_minimal_ui = 1

" disable rails plugin on vim enter, slow when used with vim-bundler
" also results in some garbage written to screen, seems a vim issue
" see https://github.com/tpope/vim-rails/issues/579 for some info
let g:rails_vim_enter = 0

" disable projectionist on vim enter, also causes garbage to be written
" to screen, also see https://github.com/tpope/vim-rails/issues/579
let g:projectionist_vim_enter = 0

" Don't add the recent files menu from MRU plugin
let MRU_Add_Menu = 0

" Use the current window to load the list of MRU files
let MRU_Use_Current_Window = 1

" Don't add git commits, private or tmp files to MRU files
let MRU_Exclude_Files = '\.git*\|^/\(private\|tmp\|var\)/.*'

" Don't fuzzy match when filtering MRU files, orders on match score
let MRU_FuzzyMatch = 0

" Tell tagbar to stop enabling ballooneval
let g:tagbar_show_balloon = 0

" Don't auto-generate tags files in every source code repo
let g:gutentags_generate_on_new = 0
let g:gutentags_generate_on_missing = 0

" But do generate when I write a file, for now anyway
" Note: Consider disabling gutentags entirely by default
let g:gutentags_generate_on_write = 1

" Tell netrw to also stop enabling ballooneval
let g:netrw_nobeval = 1

" Enable markdown folding
let g:markdown_folding=1

" Show relative paths by default in bufexplorer
let g:bufExplorerShowRelativePath = 1

" Show no name buffers in bufexplorer, I want to be able to find them easily
" Note: BufExplorer lists quickfix and location list buffers as [No Name] if
" it finds them in the buffer list. This is confusing and makes it easy to
" break things, so I'm using the vim-qf plugin to hide them from the list.
" FIXME: this probably warrants forking and fixing BufExplorer to hide them.
let g:bufExplorerShowNoName = 1

" Disable default BufExplorer key mappings (use custom mappings)
let g:bufExplorerDisableDefaultKeyMapping = 1

" Accept/close popup/completion menu with enter/cr, ah sanity, finally
let g:lexima_accept_pum_with_enter = 1

" Disable ALE linting by default, use ALEToggle to enable
let g:ale_enabled = 0

" And stop enabling balloneval, even when linting disabled!
let g:ale_set_balloons = 0

" Even when ALE is enabled, disable automatic linting as you type
" Note: linting still runs on enter, save and leave insert mode
let g:ale_lint_on_text_changed = 'never'

" Don't highlight linting errors in source, just use sign column
let g:ale_set_highlights = 0

" Only use ALE to run linters, use coc.nvim with language servers
" Note: Coc.nvim configured to send disgnostics to ALE for display
let g:ale_disable_lsp = 1

" Disable coc.nvim service at startup, use CocStart to enable
let g:coc_start_at_startup = 0

" Don't automagically colorize text, use <leader>tc to toggle
let g:Hexokinase_ftEnabled = []

" Include triple hex when colorizing text (missing from default)
let g:Hexokinase_optInPatterns = [
  \ 'full_hex',
  \ 'triple_hex',
  \ 'rgb',
  \ 'rgba',
  \ 'hsl',
  \ 'hsla',
  \ 'colour_names'
  \ ]

" Use background to highlight colours, ugly, but clearly visible
let g:Hexokinase_highlighters = ['backgroundfull']

" Tell NERDTree to respect wildignore
let NERDTreeRespectWildIgnore = 1

" Stop NERDTree from hijacking netrw, I want to use both :-)
let NERDTreeHijackNetrw = 0

" Show hidden files in NERDTree (same as netrw)
let NERDTreeShowHidden = 1

" Custom statusline for NERDTree (just show buffer name, e.g. NERD_tree_1)
" Another option to consider is to show the currently selected file, e.g.
" https://github.com/vim-airline/vim-airline/issues/271#issuecomment-40597276
let NERDTreeStatusline = '%t'

" Minimalist NERDTree UI, no bookmarks, help hint or up a dir
let NERDTreeMinimalUI = 1

" Always show the netrw banner, so it's not mistaken for NERDTree
let g:netrw_banner = 1

" Don't go back to netrw when choosing to edit the alternate file,
" actually go back to the last edited file (same as bufexplorer)
let g:netrw_altfile = 1

" Disable whitespace highlighting by default, toggle with <leader><space>
let g:better_whitespace_enabled = 0

" Automatically strip whitespace on save using better_whitespace plugin
let g:strip_whitespace_on_save = 1

" Only strip whitespace on modified lines and don't ask for confirmation
let g:strip_only_modified_lines = 1
let g:strip_whitespace_confirm = 0

" Don't autohide scratch window when leaving insert mode
let g:scratch_insert_autohide = 0

" Highlight JSX embedded in javascript files
let g:jsx_ext_required = 0

" Disable signify by default, enable as needed using gd mapping (see below)
let g:signify_disable_by_default = 1

" Disable gd mapping for GoDef command, gd = git diff, use CTRL-[ for GoDef
let g:go_def_mapping_enabled = 0

" Prefix fzf commands with FZF, e.g. Files becomes FZFFiles (avoids polluting
" top level namespace and makes it easier to find and complete FZF commands)
let g:fzf_command_prefix = 'FZF'

" Don't automatically change working directory to project root
" Just using public function FindRootDirectory() with MRU mappings
let g:rooter_manual_only = 1

" Override indent level for continuation lines in vimscript
" Default is shiftwidth() * 3, see $VIMRUNTIME/ftplugin/vim.vim
let g:vim_indent_cont = 2

if executable('glow')
  let g:markdown_preview_command = 'glow -s dark -p'
elseif executable('mdcat')
  let g:markdown_preview_command = 'mdcat -p'
else
  " FIXME should this error only appear when attempting to preview markdown???
  echoerr "WARNING: no markdown preview executable found, install glow to fix this, see https://github.com/charmbracelet/glow"
endif

if executable('rg')
  let $RIPGREP_CONFIG_PATH = expand('~/.vim/rgconfig')
  set grepprg=rg\ --vimgrep\ --smart-case\ --hidden\ --no-ignore-parent\ --ignore-file\ ~/.vim/rgignore
  set grepformat=%f:%l:%c:%m
  let $FZF_DEFAULT_COMMAND = 'rg --files --color never --no-config --hidden --no-ignore-parent --ignore-file ~/.vim/rgignore'
elseif executable('ag')
  set grepprg=ag\ --vimgrep\ --hidden
  set grepformat=%f:%l:%c:%m
  let $FZF_DEFAULT_COMMAND = 'ag --literal --files-with-matches --nocolor --hidden -g ""'
else
  echoerr "WARNING: grep alternative not found, finding files will be slow, install ripgrep to fix this, see https://github.com/BurntSushi/ripgrep"
endif

" Set bat theme for fancy syntax highlighting in FZF preview window
if executable('bat')
  " GitHub theme works well with dark and light backgrounds and color schemes
  let $BAT_THEME='GitHub'
else
  echoerr "WARNING: bat executable not found, preview window will not have syntax highlighting, install bat to fix this, see https://github.com/sharkdp/bat"
endif

" FZF color scheme, see https://github.com/junegunn/fzf/wiki/Color-schemes
function! <SID>UpdateFZFColors()
  let colors_name = get(g:, 'colors_name', 'default')
  if colors_name ==# 'solarized'
    if &background ==# 'light'
      let $FZF_DEFAULT_OPTS='
        \ --color fg:240,bg:230,hl:33,fg+:241,bg+:221,hl+:33
        \ --color info:33,prompt:33,pointer:166,marker:166,spinner:33'
    else
      let $FZF_DEFAULT_OPTS='
        \ --color dark,hl:33,hl+:37,fg+:235,bg+:136,fg+:254
        \ --color info:254,prompt:37,spinner:108,pointer:235,marker:235'
    endif
  elseif ( colors_name ==# 'jellybeans' )
    let $FZF_DEFAULT_OPTS='
      \ --color fg:188,bg:233,hl:103,fg+:222,bg+:234,hl+:104
      \ --color info:183,prompt:110,spinner:107,pointer:167,marker:215'
  elseif ( colors_name ==# 'PaperColor' )
    let $FZF_DEFAULT_OPTS='
      \ --color=light,fg:#4d4d4c,bg:#eeeeee,hl:#d7005f
      \ --color=fg+:#4d4d4c,bg+:#e8e8e8,hl+:#d7005f
      \ --color=info:#4271ae,prompt:#8959a8,pointer:#d7005f
      \ --color=marker:#4271ae,spinner:#4271ae,header:#4271ae'
  else
    let $FZF_DEFAULT_OPTS='--color ' . &background
  endif
endfunction
autocmd VimEnter,ColorScheme * call <SID>UpdateFZFColors()

" Tweak some annoying highilghting from PaperColor and solarized
autocmd VimEnter,ColorScheme *
  \ if get(g:, 'colors_name', v:null) ==# 'PaperColor' |
  \   hi Spellbad guibg=NONE guifg=NONE |
  \ elseif get(g:, 'colors_name', v:null) ==# 'solarized' |
  \   hi MatchParen ctermbg=NONE guibg=NONE |
  \   hi SpecialKey cterm=NONE ctermbg=NONE ctermfg=239 gui=NONE guibg=NONE guifg=#bcbcbc |
  \ endif

" Add cut/move mappings (delete operations overridden by vim-cutlass to just
" delete, not yank and delete, see https://github.com/svermeulen/vim-cutlass)
" Warning: breaks "m{a-zA-Z}" command to set named marks, which I don't use
nnoremap m d
xnoremap m d
nnoremap mm dd
nnoremap M D

" Use q to close the quickfix window and return to the previous window
autocmd FileType qf nnoremap <silent> <buffer> q :wincmd p<CR>:cclose<CR>:wincmd =<CR>

" Fix previous window navigation when existing quickfix window re-used
autocmd QuickFixCmdPre * if &ft == 'qf' | wincmd p | end

" Mark previous cursor position when entering visual mode, see :h m`
nnoremap v m`v
nnoremap V m`V
nnoremap <C-v> m`<C-v>
nnoremap <2-LeftMouse> m`<2-LeftMouse>
nnoremap <LeftDrag> m`<LeftDrag>

" And return to previous cursor position when leaving visual mode
" Pattern derived from https://github.com/vim/vim/commit/25def2c8
if exists('##ModeChanged')
  autocmd ModeChanged [vV\x16]*:n exe "normal! ``"
endif

" Move block selections around in visual mode with schlepp plugin
vmap <C-Up> <Plug>SchleppUp
vmap <C-Down> <Plug>SchleppDown
vmap <C-Left> <Plug>SchleppLeft
vmap <C-Right> <Plug>SchleppRight

" Tab navigation with Ctrl-Tab (only works in gui vim)
noremap <C-Tab> :tabnext<cr>
noremap <S-C-Tab> :tabprevious<cr>

" Open plugin defined alternate file, e.g. unit test for model
nnoremap <leader>a :A<CR>

" Open vim alternate file, i.e. previously edited file in window
nnoremap <Leader># :edit#<CR>

" Additional mapping for quick switching between alternate files
nnoremap <Leader><leader> <C-^>

" Search with nomagic, almost like fgrep/grep --fixed-strings, see :h nomagic
nnoremap <leader>/ /\V

" Toggle ALE linting (disabled by default)
function! ALEToggle()
  if g:ale_enabled
    ALEDisable
    echohl MoreMsg | echom 'ALE disabled' | echohl None
  else
    ALEEnable
    echohl MoreMsg | echom 'ALE enabled' | echohl None
  endif
endfunction
nnoremap <Leader>ta :call ALEToggle()<CR>

" Toggle coc.nvim service (disabled by default)
function! CocToggle()
  if coc#rpc#ready()
    echohl MoreMsg | echom 'stopping coc.nvim service' | echohl None
    call coc#rpc#stop()
  else
    echohl MoreMsg | echom 'starting coc.nvim service' | echohl None
    call coc#rpc#start_server()
  endif
endfunction
nnoremap <leader>tc :call CocToggle()<CR>

" Toggle quickfix list
function! QuickfixListToggle()
  if get(getqflist({'winid': 1}), 'winid') != 0
    cclose
  elseif getqflist() != []
    copen
  else
    echohl ErrorMsg
    echo "Quickfix List is empty."
    echohl None
  endif
endfunction
nnoremap <leader>q :call QuickfixListToggle()<CR>

" Toggle location list
function! LocationListToggle()
  if get(getloclist(winnr(), {'winid': 1}), 'winid') != 0
    lclose
  elseif getloclist(winnr()) != []
    lopen
  else
    echohl ErrorMsg
    echo "Location List is empty."
    echohl None
  endif
endfunction
nnoremap <leader>l :call LocationListToggle()<CR>

" Toggle terminal - for default shell only, other terms ignored
function! TerminalToggle()
  let termbufs = filter(term_list(), { _, bufnr -> stridx(bufname(bufnr), $SHELL) > 0 })
  if empty(termbufs)
    terminal
  else
    let termwins = filter(map(copy(termbufs), { _, bufnr -> bufwinnr(bufnr) }), 'v:val != -1')
    if empty(termwins)
      for bufnr in termbufs | exe 'sbuffer ' . bufnr | endfor
    else
      for winnr in reverse(sort(termwins)) | exe winnr . 'wincmd c' | endfor
    endif
  endif
endfunction
nnoremap <C-W>` :call TerminalToggle()<CR>
tnoremap <C-W>` <C-W>:call TerminalToggle()<CR>

" Open terminal in directory of current file
function! OpenInTerminal()
  let $OLDPWD = getcwd()
  split | silent lcd %:p:h | terminal ++curwin
endfunction
nnoremap <leader>` :call OpenInTerminal()<CR>

" Custom terminal statusline, not a normal editor window
if exists('##TerminalWinOpen')
  autocmd TerminalWinOpen * setlocal statusline=%f
endif

" Use K to show documentation in preview window.
function! ShowDocumentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction
nnoremap <silent> K :call ShowDocumentation()<CR>

" Window mappings
" switch to window pseudo-mode (uses window mode plugin, no more keyboard
" contortions - window mode automatically prefixes <C-w> to all keypresses)
nnoremap <leader>wm :WindowMode<CR>
" open vim defined alternate file in new vertial split
nnoremap <leader>w# :vsplit#<CR>
" open plugin defined alternate file in new vertial split
nnoremap <leader>wa :AV<CR>
" shortcuts for opening new splits
nnoremap <leader>ws :wincmd s<CR>
nnoremap <leader>wv :wincmd v<CR>
" rotate and exchange windows
nnoremap <leader>wr :wincmd r<CR>
nnoremap <leader>wx :wincmd x<CR>
" move horizonal split to vertical
nnoremap <leader>wl :wincmd L<CR>
" navigation with arrow keys
nnoremap <C-Up> :wincmd k<CR>
nnoremap <C-Down> :wincmd j<CR>
nnoremap <C-Left> :wincmd h<CR>
nnoremap <C-Right> :wincmd l<CR>
" resize all windows equally
nnoremap <leader>= :wincmd =<CR>
" increase/decrease window width
nnoremap > :wincmd ><CR>
nnoremap < :wincmd <<CR>

" indentation text objects, visual, select, and operator-pending modes
let g:vindent_object_XX_ii = 'ii' " inner indent level, including blank lines
let g:vindent_object_OX_ii = 'iI' " inner indent level, excluding blank lines
let g:vindent_object_XX_ai = 'ai' " an indent level and the line above
let g:vindent_object_XX_aI = 'aI' " an indent level and the lines above/below

" Experimental: indentation motions, nmap only to avoid breaking {Visual}=,
" does still break ={motion}, but I never use ={motion}, that's scary shit.
" go to next line at the same indent
nmap <silent> = <Plug>(VindentBlockMotion_OO_next)
" go to previous line of same indent
nmap <silent> g= <Plug>(VindentBlockMotion_OO_prev)
" go to prev line with different indent
nmap <silent> [= <Plug>(VindentMotion_prev_diff)
" go to next line with different indent
nmap <silent> ]= <Plug>(VindentMotion_next_diff)

" Tag navigation
" remap CTRL-] to show list when multiple matches (use tjump)
nnoremap <C-]> g<C-]>
" use CTRL-\ to jump to definition in next available window
function! JumpToTagInSplit()
  let currword = expand("<cword>")
  let startwin = winnr()
  " Move to next window with a normal buffer
  let c = 0
  let n = winnr('$')
  while c < n
    exec 'wincmd w'
    if empty(getbufvar(+expand("<abuf>"), "&buftype"))
      break
    endif
    let c = c + 1
  endwhile
  " Back where we started? Open a new split
  if winnr() == startwin
    exec 'wincmd v'
  endif
  try
    exec "tjump ".currword
  catch
    " Go back to startwin on error
    exec startwin . "wincmd w"
    echoerr v:exception
  endtry
endfunction
nnoremap <C-\> :call JumpToTagInSplit()<CR>

" Toggle project drawer / tree view
" FIXME: update to use NERDTreeFind if buffer has file
nnoremap <leader>d :NERDTreeToggle<CR>

" Show/hide diff/changes in sign column
nnoremap <leader>td :SignifyToggle<CR>

" Toggle file explorer (Netrw)
function! NetrwToggle()
  if &ft == 'netrw'
    Rexplore
  else
    Explore
  end
endfunction
nnoremap <Leader>e :call NetrwToggle()<CR>

" I think I needed to set this for VimspectorInstall to work properly
" FIXME: investigate why this was necessary, docs suggest it should not be
let g:vimspector_base_dir = expand('~/.vim/bundle/vimspector')

" Launch graphical debugger/inspector (vimspector)
nmap <Leader>i <Plug>VimspectorLaunch

" Stop FZF opening files in nofile and quickfix windows, with some exceptions
let g:fzf_reuse_windows = ['bufexplorer', 'mru']
function! FZFOpen(cmd)
  let c = 0
  let wincount = winnr('$')
  while ( !empty(&buftype) && index(g:fzf_reuse_windows, &ft) == -1 && c < wincount )
    wincmd w
    let c = c + 1
  endwhile
  exec g:fzf_command_prefix . a:cmd
endfunc

" Fuzzy find files
nnoremap <leader>ff :call FZFOpen('Files')<CR>

" Fuzzy find buffers
nnoremap <leader>fb :call FZFOpen('Buffers')<CR>

" Fuzzy find commits
nnoremap <leader>fc :call FZFOpen('Commits')<CR>

" Fuzzy find commands (things to "execute")
nnoremap <leader>fe :call FZFOpen('Commands')<CR>

" Fuzzy find git ls-files
nnoremap <leader>fg :call FZFOpen('GitFiles')<CR>

" Fuzzy find help tags
nnoremap <leader>fh :call FZFOpen('Helptags')<CR>

" Fuzzy find most recently used files within project root directory
" Note: relies on MRU plugin, use <leader>fm to fzf find all MRU files
command! FZFRecent :call fzf#run(fzf#wrap({'source': MruGetFiles(FindRootDirectory()), 'sink': 'e'}))
nnoremap <leader>fr :call FZFOpen('Recent')<CR>

" Fuzzy find most recently used files
nnoremap <leader>fm :call FZFOpen('Mru')<CR>

" Fuzzy find tags
nnoremap <leader>ft :call FZFOpen('Tags')<CR>

" Custom grep prompt, inspired by vim-grepper, but simpler, just runs grepprg
" silently to avoid the "Press ENTER to continue" prompt after running external
" commands and escapes cmdline special chars to avoid expansion of # and friends
function! GrepPrompt(...)
  let inputstr = trim(input('grep> ', (a:0 > 0 ? a:1 : ''), 'customlist,GrepComplete'))
  if empty(inputstr) | redraw! | return | end
  try
    exec 'silent grep! '. escape(inputstr, '#%')
  catch /E40:/ " shell error, re-run unsilent to see error output
    try
      exec 'unsilent grep! '. escape(inputstr, '#%')
    catch /E40:/
      call setqflist([], 'r', {'title': &grepprg . ' ' . inputstr, 'items': []})
    endtry
  endtry
  redraw! | copen
endfunction

" Simple completion for grep prompt, also inspired by vim-grepper
function! GrepComplete(lead, _line, _pos)
  let args = split(a:lead, '.*\s\zs', 1)
  if len(args) < 2 | return [] | end
  let path = args[-1]
  let head = join(args[0:-2])
  return map(getcompletion(args[-1], 'file'), 'head . fnameescape(v:val)')
endfun

" Search in files using grep program, see :help grepprg and :help grep
nnoremap <leader>s :call GrepPrompt()<CR>

" Search in files for word or WORD under cursor
nnoremap <leader>y :call GrepPrompt(expand('<cword>'))<CR>
" Note: shell escape WORD to prevent expansion
nnoremap <leader>Y :call GrepPrompt(shellescape(expand('<cWORD>')))<CR>

" List projects, only used in GUI vim, see gvimrc
if has('gui_running')
  nnoremap <leader>p :SessionSave<CR>:SessionList<CR>
endif

" List open files/buffers
nnoremap <leader>b :ToggleBufExplorer<CR>

" List most recently used files
nnoremap <leader>m :MRUToggle<CR>

" List most recently used files within project root directory
nnoremap <leader>r :exec ':MRU ' . FindRootDirectory()<CR>

" Outline view of current file
nnoremap <leader>o :TagbarToggle<CR>

" Zoom in/out current window
function! ZoomWinChanged(state) abort
  if a:state
    let g:ZoomWin_statusline = '[ZoomWin]'
  else
    let g:ZoomWin_statusline = ''
  endif
endfunction
let g:ZoomWin_funcref= function('ZoomWinChanged')
nnoremap <leader>z :ZoomWin<CR>

" Expand/maximize current window
" See https://stackoverflow.com/a/26551079/17278003
function! ExpandWin() abort
  if winnr('$') == 1 | return | endif
  if exists('w:expanded') && w:expanded
    execute w:expand_winrestcmd
    let w:expanded = 0
  else
    let w:expand_winrestcmd = winrestcmd()
    resize
    vertical resize
    let w:expanded = 1
  endif
endfunction
autocmd WinLeave * if exists('w:expanded') && w:expanded | call ExpandWin() | endif
nnoremap <Leader>x :call ExpandWin()<CR>

" Highlight whitespace
nnoremap <leader><space> :ToggleWhitespace<CR>

" Toggle spell checking
nnoremap <Leader>ts :setlocal spell!<CR>

" Toggle list mode (show whitespace)
nnoremap <Leader>tw :setlocal list!<CR>

" Toggle colorizing of color codes and names
" Note: Hexokinase requires termguicolors
nnoremap <leader>th :set termguicolors!<CR>:HexokinaseToggle<CR>

" Toggle indent guides / lines
nnoremap <leader>ti :IndentLinesToggle<CR>

" Some extra mappings for convenience/speed
" Single key to toggle bufexplorer, I use this all the time
nnoremap ; :ToggleBufExplorer<CR>

" Remap gs to open Scratch window in normal rather than insert mode
let g:scratch_no_mappings = 1 " must disable plugin mappings first
nnoremap gs :Scratch<CR>

if exists('##TerminalWinOpen')
  " Make p paste from unanmed register in terminal normal mode
  au TerminalWinOpen *
    \ nnoremap <silent> <buffer> p :call term_sendkeys('', getreg()) \| normal! A<CR>
endif

" Custom filetype detection, runs after built in filetype detection
" Using augroup filetypedetect means this re-runs on :filetype detect,
" which means it works after restoring a macvim session (see gvimrc).
augroup filetypedetect
  " Set .asc to AsciiDoc as this is recognised by GitHub (Vim only recognises
  " .asciidoc and .adoc extensions by default, see $VIMRUNTIME/filetype.vim)
  autocmd BufRead,BufNewFile *.asc setfiletype asciidoc

  " Additional ruby syntax highlighting
  autocmd BufRead,BufNewFile {Berksfile,Capfile,Vagrantfile,Thorfile,pryrc,.pryrc,*.cap}
    \ setfiletype ruby |

  " Set cloudformation filetypes to enable linting in ALE
  autocmd Filetype yaml,json
    \ if search('AWSTemplateFormatVersion', 'nwc') |
    \   let &ft=&ft . '.cloudformation' |
    \ endif

  " Set conf.local filetype to conf
  autocmd BufRead,BufNewFile *.conf.local setfiletype conf

  " Crude autodetection of some common rc and other dotfile types/formats
  autocmd BufRead,BufWrite .*rc,$HOME/.*
    \ if empty(&ft) |
    \   if getline(1) =~ '^{' |
    \     setfiletype json |
    \   elseif getline(1) == '---' |
    \     setfiletype yaml |
    \   elseif getline(1) =~ '^\w\+:' && ( getline(2) =~ '^\w\+:' || getline(2) =~ '^\s\+\-\s\+\w\+' ) |
    \     setfiletype yaml |
    \   elseif search('^\[.*\]', 'nw') && search('^\w\+\s*=\s*\(\w\|\"\)', 'nwc') |
    \     setfiletype dosini |
    \   endif |
    \ endif

  " Even cruder autodetection of text files with no file extension
  autocmd BufRead,BufWrite *
    \ if empty(&ft) && empty(expand('%:e')) && search('\c^\(\w\+\s\+\)\{2}\w\+', 'nwc', 10) |
    \   setfiletype text |
    \ endif
augroup END

" Mapping to load markdown preview in popup window
autocmd FileType markdown
  \ nnoremap <buffer> <leader>v :silent execute 'FloatermNew --disposable --title='. expand('%:~:.') . ' ' . g:markdown_preview_command . ' %'<CR>

" Use html omnicompletion for xhtml documents
autocmd FileType xhtml set omnifunc=htmlcomplete#CompleteTags

" Use xmllint as exernal program for formatting xml
autocmd FileType xml setlocal formatprg=xmllint\ --format\ --recover\ -\ 2>/dev/null

" Use jsonlint as external program for formatting json
autocmd FileType json setlocal formatprg=jsonlint\ --pretty-print\ 2>/dev/null

" Use auopep8 for formatting python, customise using ~/.config/pycodestyle
" TODO: automatically use black formatter if configured in pyproject.toml,
" and consider passing textwidth as max line length (changed by editorconfig)
autocmd FileType python setlocal formatprg=autopep8\ -\ 2>/dev/null

" Disable yaml indentexpr from runtime files, too magical and confusing for
" occasional use. See https://groups.google.com/g/vim_dev/c/vgNNI-pj7Gk?pli=1
autocmd FileType yaml setlocal autoindent indentexpr=

" Use syntax based completion when no omnicompletion available
if exists("+omnifunc")
  autocmd Filetype *
    \	if &omnifunc == "" |
    \	  setlocal omnifunc=syntaxcomplete#Complete |
    \	endif
endif

" Subtly highlight long lines rather than display colorcolumn
function! <SID>HighlightLongLines()
  for l:match in getmatches()
    if get(l:match, 'group', '') == 'ColorColumn'
      call matchdelete(get(l:match, 'id'))
    endif
  endfor
  if &textwidth > 0
    call matchadd('ColorColumn', '\%'.(&tw+1).'v.\+', -1)
  endif
endfunction
if exists('##OptionSet')
  " Apply long line highlighting whenever textwidth option is set
  autocmd OptionSet textwidth call <SID>HighlightLongLines()
  " And on VimEnter because OptionSet autocmds do not run on startup
  autocmd VimEnter * bufdo call <SID>HighlightLongLines()
endif

" Diff a buffer with the file from which it was originally loaded
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
    \ | wincmd p | diffthis
endif

" Set working directory when opening vim, use directory of current file when
" provided as argument, otherwise cwd to root of project/package if possible.
" Note: uses vim-rooter, and works nicely with monorepos (not reliant on VCS)
function! <SID>SetWorkingDir()
  if argc() == 1 && len(argv()) == 1
    if isdirectory(argv(0))
      exec 'cd' argv(0)
    elseif filereadable(argv(0))
      exec 'cd %:p:h'
    end
  elseif len(argv()) == 0
    let l:root = FindRootDirectory()
    if l:root !=# getcwd()
      exec 'cd' l:root
    endif
  endif
  exec 'pwd'
endfunction
autocmd VimEnter * call <SID>SetWorkingDir()
