#!/bin/bash

if test "$(uname)" == "Darwin" ; then
  brew install bash-completion
fi

for file in .bash_profile .bash_login .profile; do
  if test -f "$HOME/$file"; then
    if ! fgrep "source ~/dotfiles/bash/profile" ~/$file &> /dev/null; then
      echo "" >> ~/$file
      echo "source ~/dotfiles/bash/profile" >> ~/$file
    fi
    break
  fi
done
