#!/bin/bash

set -x

if test "$(uname)" == "Darwin" ; then
  brew install bash bash-completion
fi

touch ~/.bash_profile
if ! fgrep "source ~/dotfiles/bash/profile" ~/.bash_profile &> /dev/null; then
  echo "" >> ~/.bash_profile
  echo "source ~/dotfiles/bash/profile" >> ~/.bash_profile
fi
